[package]
name = "Rust_Sobel_Convolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.0"
pbr = "1.0.1"
clap = {version = "2.32", features = ["yaml"]}
ndarray = "0.9.1"
